#pragma once
// Generated from version.xml. Do not edit this file directly.
#define MVVIEW_VERSION_MAJOR 0
#define MVVIEW_VERSION_MINOR 30
#define MVVIEW_VERSION_PATCH 0
#define MVVIEW_VERSION_BUILD 0
#define MVVIEW_VERSION_TEXT "0.30"
#define MVVIEW_VERSION_TEXT_W L"0.30"
#define MVVIEW_DISPLAY_VERSION_W L"v0.30"
#define MVVIEW_APP_DISPLAY_NAME_W L"MvView v0.30"
